In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import cv2
import os

DATADIR = "C:/Users/skzt/Documents/TCC/fotos"
IMG_SIZE_X = 50
IMG_SIZE_Y = 15

def printArray(arr,x, y):
    for i in range(y):
        tmp = ''
        for j in range(x):
            tmp += str(arr[i][j])
            tmp += ' '
        print(tmp)

a = cv2.imread(os.path.join(DATADIR, "teste5"".png"), cv2.IMREAD_GRAYSCALE)
b = cv2.resize(a, (IMG_SIZE_X, IMG_SIZE_Y))
plt.imshow(b, cmap="gray")
plt.show()
# TODO: criar array de treino, separan
num1 = []
num2 = []
num3 = []
num4 = []

for i in range(IMG_SIZE_Y):
    tmp1 = []
    tmp2 = []
    tmp3 = []
    tmp4 = []
    for j in range(24, IMG_SIZE_X):
        if j <= 29:
            tmp1.append(b[i][j])
        elif j <= 35:
            tmp2.append(b[i][j])
        elif j <= 41:
            tmp3.append(b[i][j])
        elif j <= 47:
            tmp4.append(b[i][j])
        else:
            continue
    num1.append(tmp1)
    num2.append(tmp2)
    num3.append(tmp3)
    num4.append(tmp4)
    
num1 = np.array(num1)
num2 = np.array(num2)
num3 = np.array(num3)
num4 = np.array(num4)


In [ ]:


plt.imshow(num1, cmap="gray")
plt.show()
plt.imshow(num2, cmap="gray")
plt.show()
plt.imshow(num3, cmap="gray")
plt.show()
plt.imshow(num4, cmap="gray")
plt.show()



In [8]:
import numpy as np
x = np.load(f"training_data-30-03-(15, 50)-0.01.npy")

x = x[:3]
x = [i[0] for i in x]
x = np.array(x)
print(x)
x = x.reshape(-1, 15,6, 1)
print(x)

a = ["IMG1", "IMG2", "IMG3", "IMG4", "IMG5", "IMG6" ]
a = np.array(a)
print(a)
print(a[0])
a = a.reshape(-1,3,2,1)
print(a.shape)
print("\n------------------------------------------\n",a[0])

[[[100 100  99 102 110 112]
  [ 95  97 100 103 108 108]
  [ 85  93 103 106 103 103]
  [ 84  90  97  99  96  98]
  [ 88  88  88  87  88  92]
  [ 74  73  71  69  69  74]
  [ 55  55  53  50  48  53]
  [ 63  64  69  68  61  60]
  [ 70  73  85  85  73  68]
  [ 64  65  68  67  62  64]
  [ 61  60  56  54  54  62]
  [ 66  65  61  60  62  68]
  [ 71  69  66  65  66  70]
  [ 71  70  67  65  65  67]
  [ 72  70  67  65  64  65]]

 [[ 93 101 105 104 104 106]
  [102 106 107 106 105 105]
  [115 115 115 112 109 107]
  [127 132 137 130 122 117]
  [118 116 107 113 118 117]
  [104  97  69  90 110 114]
  [ 99  95  58  82 105 111]
  [101  94  53  80 106 114]
  [105  95  52  80 109 116]
  [105  99  55  82 108 115]
  [105 100  56  83 110 119]
  [108 102  62  87 112 122]
  [120 113  88  99 112 119]
  [114 115 109 113 118 121]
  [106 114 124 124 123 125]]

 [[188 206 222 225 225 226]
  [200 214 228 230 230 230]
  [216 224 232 234 234 232]
  [233 233 232 233 233 230]
  [233 230 220 212 221 216]
  [232 217 194 1